insert into products (price, quantity, sku, title) values
                                                       (12.4, 4, 'parle734', 'Parle-G'),
                                                       (14.4, 1, 'pepsi123', 'Pepsi'),
                                                       (34.4, 1, 'coke123', 'Coca Cola'),
                                                       (16.4, 3, 'pepsi156', 'Maaza'),
                                                       (22.5, 5, 'lays876', 'Lays Classic'),
                                                       (18.9, 2, 'uncle441', 'Uncle Chips'),
                                                       (45.0, 3, 'kitkat52', 'KitKat'),
                                                       (29.9, 4, 'dairy765', 'Dairy Milk'),
                                                       (15.5, 6, 'kurkure1', 'Kurkure'),
                                                       (25.0, 2, 'oreo333', 'Oreo'),
                                                       (19.9, 5, 'sprite44', 'Sprite'),
                                                       (32.5, 3, 'fanta123', 'Fanta'),
                                                       (28.7, 4, '7up4321', '7Up'),
                                                       (21.5, 2, 'thums123', 'Thumbs Up'),
                                                       (17.8, 5, 'bingo567', 'Bingo Mad Angles'),
                                                       (39.9, 1, 'snick123', 'Snickers'),
                                                       (26.5, 3, 'mars456', 'Mars'),
                                                       (23.4, 4, 'hide234', 'Hide & Seek'),
                                                       (31.2, 2, 'bourb123', 'Bourbon'),
                                                       (16.9, 5, 'good234', 'Good Day'),
                                                       (27.8, 3, 'jim5678', 'Jim Jam'),
                                                       (20.5, 4, 'dark123', 'Dark Fantasy'),
                                                       (35.6, 2, 'milky23', 'Milky Bar'),
                                                       (24.9, 3, 'cadbu567', 'Cadbury 5 Star');